server:
  port: 9000
  resource: /root/resource

spring:
  datasource:
    name: Forum_database
    url: jdbc:mysql://8.130.76.6/Forum_database
    username: root
    password: GC20011228sh!
    driver-class-name: com.mysql.cj.jdbc.Driver

#操作oss需要的一些参数
aliyun:
  accessKeyId: LTAI5t7Z7N2WvVGbJ2ftPSWY       # 阿里云的accessKeyId
  secretAccessKey: TNLk9Q10CE8eKEzLQP1k0pxQrIFB9b   # accessKey 密码
  oss:
    endPoint: oss-cn-hangzhou.aliyuncs.com     # Endpoint:在阿里云oss控制台查看自己使用的endpoint
    bucketName: scott-gc   # bucket 名称

#MyBatis-Plus配置
#mybatis-plus:
  #configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#logging:
  #level:
   # com.baomidou.mybatisplus.core: DEBUG

