server:
  port: 9000
  resource: /root/resource



#MyBatis-Plus配置
#mybatis-plus:
  #configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#logging:
  #level:
   # com.baomidou.mybatisplus.core: DEBUG

